name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

env:
  CIBW_TEST_COMMAND: pytest {project}/tests
  CIBW_TEST_REQUIRES: pytest
  CIBW_BUILD: "cp38-manylinux_x86_64 wheel" # Skip PyPy, 32-bit builds
  CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.14

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Manual build
      run: pip install ./

    - uses: pypa/cibuildwheel@v2.4.0

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
